# Generated by Django 3.2.7 on 2021-10-06 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meals',
            name='carbs',
        ),
        migrations.RemoveField(
            model_name='meals',
            name='meat',
        ),
        migrations.RemoveField(
            model_name='meals',
            name='side_dish',
        ),
    ]
